# Generated by Django 4.1.5 on 2023-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='see/'),
        ),
    ]
